/** @file devnet chainInfo fixture */

/**
 * @import {CosmosChainInfo} from '@agoric/orchestration';
 */

/**
 * built with:
 *
 * agoric run src/chain-info.build.js   --net=devnet --peer=noble:connection-13:channel-11:uusdc   --peer=axelar:connection-19:channel-315:uaxl
 *
 * @type {Record<string, CosmosChainInfo>}
 */
export const chainInfoDevNet = {
  agoric: {
    bech32Prefix: 'agoric',
    chainId: 'agoricdev-25',
    connections: {
      'axelar-testnet-lisbon-3': {
        client_id: '07-tendermint-22',
        counterparty: {
          client_id: '07-tendermint-1193',
          connection_id: 'connection-942',
        },
        id: 'connection-19',
        state: 3, // 'STATE_OPEN'
        transferChannel: {
          channelId: 'channel-315',
          counterPartyChannelId: 'channel-623',
          counterPartyPortId: 'transfer',
          ordering: 0, // 'ORDER_UNORDERED'
          portId: 'transfer',
          state: 3, // 'STATE_OPEN'
          version: 'ics20-1',
        },
      },
      'grand-1': {
        client_id: '07-tendermint-13',
        counterparty: {
          client_id: '07-tendermint-432',
          connection_id: 'connection-396',
        },
        id: 'connection-13',
        state: 3, // 'STATE_OPEN',
        transferChannel: {
          channelId: 'channel-11',
          counterPartyChannelId: 'channel-337',
          counterPartyPortId: 'transfer',
          ordering: 0, // 'ORDER_UNORDERED'
          portId: 'transfer',
          state: 3, // 'STATE_OPEN',
          version: 'ics20-1',
        },
      },
    },
    namespace: 'cosmos',
    reference: 'agoricdev-25',
    stakingTokens: [
      {
        denom: 'ubld',
      },
    ],
  },
  axelar: {
    bech32Prefix: 'axelar',
    chainId: 'axelar-testnet-lisbon-3',
    namespace: 'cosmos',
    reference: 'axelar-testnet-lisbon-3',
    stakingTokens: [
      {
        denom: 'uaxl',
      },
    ],
  },
  noble: {
    bech32Prefix: 'noble',
    chainId: 'grand-1',
    namespace: 'cosmos',
    reference: 'grand-1',
    stakingTokens: [
      {
        denom: 'uusdc',
      },
    ],
  },
};

harden(chainInfoDevNet);

/**
 * https://www.mintscan.io/agoric/proposals/100 Jul 18th 2025
 *
 * @type {Record<string, CosmosChainInfo>}
 */
export const chainInfoProposal100 = {
  agoric: {
    bech32Prefix: 'agoric',
    chainId: 'agoric-3',
    connections: {
      'axelar-dojo-1': {
        client_id: '07-tendermint-11',
        counterparty: {
          client_id: '07-tendermint-69',
          connection_id: 'connection-51',
        },
        id: 'connection-14',
        state: 3,
        transferChannel: {
          channelId: 'channel-9',
          counterPartyChannelId: 'channel-41',
          counterPartyPortId: 'transfer',
          ordering: 0,
          portId: 'transfer',
          state: 3,
          version: 'ics20-1',
        },
      },
      'core-1': {
        client_id: '07-tendermint-93',
        counterparty: {
          client_id: '07-tendermint-167',
          connection_id: 'connection-210',
        },
        id: 'connection-91',
        state: 3,
        transferChannel: {
          channelId: 'channel-72',
          counterPartyChannelId: 'channel-202',
          counterPartyPortId: 'transfer',
          ordering: 0,
          portId: 'transfer',
          state: 3,
          version: 'ics20-1',
        },
      },
      'cosmoshub-4': {
        client_id: '07-tendermint-6',
        counterparty: {
          client_id: '07-tendermint-927',
          connection_id: 'connection-649',
        },
        id: 'connection-8',
        state: 3,
        transferChannel: {
          channelId: 'channel-5',
          counterPartyChannelId: 'channel-405',
          counterPartyPortId: 'transfer',
          ordering: 0,
          portId: 'transfer',
          state: 3,
          version: 'ics20-1',
        },
      },
      'crescent-1': {
        client_id: '07-tendermint-2',
        counterparty: {
          client_id: '07-tendermint-19',
          connection_id: 'connection-14',
        },
        id: 'connection-2',
        state: 3,
        transferChannel: {
          channelId: 'channel-2',
          counterPartyChannelId: 'channel-11',
          counterPartyPortId: 'transfer',
          ordering: 0,
          portId: 'transfer',
          state: 3,
          version: 'ics20-1',
        },
      },
      'evmos_9001-2': {
        client_id: '07-tendermint-72',
        counterparty: {
          client_id: '07-tendermint-116',
          connection_id: 'connection-70',
        },
        id: 'connection-66',
        state: 3,
        transferChannel: {
          channelId: 'channel-57',
          counterPartyChannelId: 'channel-85',
          counterPartyPortId: 'transfer',
          ordering: 0,
          portId: 'transfer',
          state: 3,
          version: 'ics20-1',
        },
      },
      'kaiyo-1': {
        client_id: '07-tendermint-20',
        counterparty: {
          client_id: '07-tendermint-94',
          connection_id: 'connection-64',
        },
        id: 'connection-20',
        state: 3,
        transferChannel: {
          channelId: 'channel-13',
          counterPartyChannelId: 'channel-61',
          counterPartyPortId: 'transfer',
          ordering: 0,
          portId: 'transfer',
          state: 3,
          version: 'ics20-1',
        },
      },
      'kava_2222-10': {
        client_id: '07-tendermint-78',
        counterparty: {
          client_id: '07-tendermint-147',
          connection_id: 'connection-182',
        },
        id: 'connection-73',
        state: 3,
        transferChannel: {
          channelId: 'channel-63',
          counterPartyChannelId: 'channel-133',
          counterPartyPortId: 'transfer',
          ordering: 0,
          portId: 'transfer',
          state: 3,
          version: 'ics20-1',
        },
      },
      'neutron-1': {
        client_id: '07-tendermint-101',
        counterparty: {
          client_id: '07-tendermint-148',
          connection_id: 'connection-108',
        },
        id: 'connection-99',
        state: 3,
        transferChannel: {
          channelId: 'channel-146',
          counterPartyChannelId: 'channel-5789',
          counterPartyPortId: 'transfer',
          ordering: 0,
          portId: 'transfer',
          state: 3,
          version: 'ics20-1',
        },
      },
      'noble-1': {
        client_id: '07-tendermint-77',
        counterparty: {
          client_id: '07-tendermint-32',
          connection_id: 'connection-38',
        },
        id: 'connection-72',
        state: 3,
        transferChannel: {
          channelId: 'channel-62',
          counterPartyChannelId: 'channel-21',
          counterPartyPortId: 'transfer',
          ordering: 0,
          portId: 'transfer',
          state: 3,
          version: 'ics20-1',
        },
      },
      'omniflixhub-1': {
        client_id: '07-tendermint-73',
        counterparty: {
          client_id: '07-tendermint-47',
          connection_id: 'connection-40',
        },
        id: 'connection-67',
        state: 3,
        transferChannel: {
          channelId: 'channel-58',
          counterPartyChannelId: 'channel-30',
          counterPartyPortId: 'transfer',
          ordering: 0,
          portId: 'transfer',
          state: 3,
          version: 'ics20-1',
        },
      },
      'osmosis-1': {
        client_id: '07-tendermint-1',
        counterparty: {
          client_id: '07-tendermint-2109',
          connection_id: 'connection-1649',
        },
        id: 'connection-1',
        state: 3,
        transferChannel: {
          channelId: 'channel-1',
          counterPartyChannelId: 'channel-320',
          counterPartyPortId: 'transfer',
          ordering: 0,
          portId: 'transfer',
          state: 3,
          version: 'ics20-1',
        },
      },
      'quicksilver-2': {
        client_id: '07-tendermint-85',
        counterparty: {
          client_id: '07-tendermint-84',
          connection_id: 'connection-60',
        },
        id: 'connection-85',
        state: 3,
        transferChannel: {
          channelId: 'channel-68',
          counterPartyChannelId: 'channel-125',
          counterPartyPortId: 'transfer',
          ordering: 0,
          portId: 'transfer',
          state: 3,
          version: 'ics20-1',
        },
      },
      'secret-4': {
        client_id: '07-tendermint-17',
        counterparty: {
          client_id: '07-tendermint-111',
          connection_id: 'connection-80',
        },
        id: 'connection-17',
        state: 3,
        transferChannel: {
          channelId: 'channel-10',
          counterPartyChannelId: 'channel-51',
          counterPartyPortId: 'transfer',
          ordering: 0,
          portId: 'transfer',
          state: 3,
          version: 'ics20-1',
        },
      },
      'stride-1': {
        client_id: '07-tendermint-74',
        counterparty: {
          client_id: '07-tendermint-129',
          connection_id: 'connection-118',
        },
        id: 'connection-68',
        state: 3,
        transferChannel: {
          channelId: 'channel-59',
          counterPartyChannelId: 'channel-148',
          counterPartyPortId: 'transfer',
          ordering: 0,
          portId: 'transfer',
          state: 3,
          version: 'ics20-1',
        },
      },
      'umee-1': {
        client_id: '07-tendermint-18',
        counterparty: {
          client_id: '07-tendermint-152',
          connection_id: 'connection-101',
        },
        id: 'connection-18',
        state: 3,
        transferChannel: {
          channelId: 'channel-11',
          counterPartyChannelId: 'channel-42',
          counterPartyPortId: 'transfer',
          ordering: 0,
          portId: 'transfer',
          state: 3,
          version: 'ics20-1',
        },
      },
    },
    icqEnabled: false,
    namespace: 'cosmos',
    reference: 'agoric-3',
    stakingTokens: [
      {
        denom: 'ubld',
      },
    ],
  },
  axelar: {
    bech32Prefix: 'axelar',
    chainId: 'axelar-dojo-1',
    connections: {
      'agoric-3': {
        client_id: '07-tendermint-69',
        counterparty: {
          client_id: '07-tendermint-11',
          connection_id: 'connection-14',
        },
        id: 'connection-51',
        state: 3,
        transferChannel: {
          channelId: 'channel-41',
          counterPartyChannelId: 'channel-9',
          counterPartyPortId: 'transfer',
          ordering: 0,
          portId: 'transfer',
          state: 3,
          version: 'ics20-1',
        },
      },
      celestia: {
        client_id: '07-tendermint-185',
        counterparty: {
          client_id: '07-tendermint-9',
          connection_id: 'connection-1',
        },
        id: 'connection-163',
        state: 3,
        transferChannel: {
          channelId: 'channel-125',
          counterPartyChannelId: 'channel-1',
          counterPartyPortId: 'transfer',
          ordering: 0,
          portId: 'transfer',
          state: 3,
          version: 'ics20-1',
        },
      },
      'coreum-mainnet-1': {
        client_id: '07-tendermint-179',
        counterparty: {
          client_id: '07-tendermint-7',
          connection_id: 'connection-7',
        },
        id: 'connection-157',
        state: 3,
        transferChannel: {
          channelId: 'channel-120',
          counterPartyChannelId: 'channel-6',
          counterPartyPortId: 'transfer',
          ordering: 0,
          portId: 'transfer',
          state: 3,
          version: 'ics20-1',
        },
      },
      'cosmoshub-4': {
        client_id: '07-tendermint-3',
        counterparty: {
          client_id: '07-tendermint-622',
          connection_id: 'connection-481',
        },
        id: 'connection-2',
        state: 3,
        transferChannel: {
          channelId: 'channel-2',
          counterPartyChannelId: 'channel-293',
          counterPartyPortId: 'transfer',
          ordering: 0,
          portId: 'transfer',
          state: 3,
          version: 'ics20-1',
        },
      },
      'crescent-1': {
        client_id: '07-tendermint-31',
        counterparty: {
          client_id: '07-tendermint-6',
          connection_id: 'connection-4',
        },
        id: 'connection-17',
        state: 3,
        transferChannel: {
          channelId: 'channel-7',
          counterPartyChannelId: 'channel-4',
          counterPartyPortId: 'transfer',
          ordering: 0,
          portId: 'transfer',
          state: 3,
          version: 'ics20-1',
        },
      },
      'dymension_1100-1': {
        client_id: '07-tendermint-197',
        counterparty: {
          client_id: '07-tendermint-7',
          connection_id: 'connection-6',
        },
        id: 'connection-180',
        state: 3,
        transferChannel: {
          channelId: 'channel-138',
          counterPartyChannelId: 'channel-5',
          counterPartyPortId: 'transfer',
          ordering: 0,
          portId: 'transfer',
          state: 3,
          version: 'ics20-1',
        },
      },
      'empowerchain-1': {
        client_id: '07-tendermint-158',
        counterparty: {
          client_id: '07-tendermint-2',
          connection_id: 'connection-2',
        },
        id: 'connection-142',
        state: 3,
        transferChannel: {
          channelId: 'channel-109',
          counterPartyChannelId: 'channel-2',
          counterPartyPortId: 'transfer',
          ordering: 0,
          portId: 'transfer',
          state: 3,
          version: 'ics20-1',
        },
      },
      'evmos_9001-2': {
        client_id: '07-tendermint-50',
        counterparty: {
          client_id: '07-tendermint-69',
          connection_id: 'connection-27',
        },
        id: 'connection-31',
        state: 3,
        transferChannel: {
          channelId: 'channel-22',
          counterPartyChannelId: 'channel-21',
          counterPartyPortId: 'transfer',
          ordering: 0,
          portId: 'transfer',
          state: 3,
          version: 'ics20-1',
        },
      },
      'haqq_11235-1': {
        client_id: '07-tendermint-162',
        counterparty: {
          client_id: '07-tendermint-1',
          connection_id: 'connection-1',
        },
        id: 'connection-148',
        state: 3,
        transferChannel: {
          channelId: 'channel-113',
          counterPartyChannelId: 'channel-1',
          counterPartyPortId: 'transfer',
          ordering: 0,
          portId: 'transfer',
          state: 3,
          version: 'ics20-1',
        },
      },
      'injective-1': {
        client_id: '07-tendermint-37',
        counterparty: {
          client_id: '07-tendermint-113',
          connection_id: 'connection-93',
        },
        id: 'connection-20',
        state: 3,
        transferChannel: {
          channelId: 'channel-10',
          counterPartyChannelId: 'channel-84',
          counterPartyPortId: 'transfer',
          ordering: 0,
          portId: 'transfer',
          state: 3,
          version: 'ics20-1',
        },
      },
      'juno-1': {
        client_id: '07-tendermint-25',
        counterparty: {
          client_id: '07-tendermint-150',
          connection_id: 'connection-97',
        },
        id: 'connection-14',
        state: 3,
        transferChannel: {
          channelId: 'channel-4',
          counterPartyChannelId: 'channel-71',
          counterPartyPortId: 'transfer',
          ordering: 0,
          portId: 'transfer',
          state: 3,
          version: 'ics20-1',
        },
      },
      'kaiyo-1': {
        client_id: '07-tendermint-42',
        counterparty: {
          client_id: '07-tendermint-11',
          connection_id: 'connection-6',
        },
        id: 'connection-23',
        state: 3,
        transferChannel: {
          channelId: 'channel-14',
          counterPartyChannelId: 'channel-9',
          counterPartyPortId: 'transfer',
          ordering: 0,
          portId: 'transfer',
          state: 3,
          version: 'ics20-1',
        },
      },
      'lava-mainnet-1': {
        client_id: '07-tendermint-225',
        counterparty: {
          client_id: '07-tendermint-0',
          connection_id: 'connection-0',
        },
        id: 'connection-210',
        state: 3,
        transferChannel: {
          channelId: 'channel-156',
          counterPartyChannelId: 'channel-0',
          counterPartyPortId: 'transfer',
          ordering: 0,
          portId: 'transfer',
          state: 3,
          version: 'ics20-1',
        },
      },
      'migaloo-1': {
        client_id: '07-tendermint-180',
        counterparty: {
          client_id: '07-tendermint-101',
          connection_id: 'connection-80',
        },
        id: 'connection-158',
        state: 3,
        transferChannel: {
          channelId: 'channel-121',
          counterPartyChannelId: 'channel-53',
          counterPartyPortId: 'transfer',
          ordering: 0,
          portId: 'transfer',
          state: 3,
          version: 'ics20-1',
        },
      },
      'neutron-1': {
        client_id: '07-tendermint-123',
        counterparty: {
          client_id: '07-tendermint-1',
          connection_id: 'connection-1',
        },
        id: 'connection-110',
        state: 3,
        transferChannel: {
          channelId: 'channel-78',
          counterPartyChannelId: 'channel-2',
          counterPartyPortId: 'transfer',
          ordering: 0,
          portId: 'transfer',
          state: 3,
          version: 'ics20-1',
        },
      },
      'omniflixhub-1': {
        client_id: '07-tendermint-122',
        counterparty: {
          client_id: '07-tendermint-44',
          connection_id: 'connection-37',
        },
        id: 'connection-109',
        state: 3,
        transferChannel: {
          channelId: 'channel-77',
          counterPartyChannelId: 'channel-27',
          counterPartyPortId: 'transfer',
          ordering: 0,
          portId: 'transfer',
          state: 3,
          version: 'ics20-1',
        },
      },
      'osmosis-1': {
        client_id: '07-tendermint-23',
        counterparty: {
          client_id: '07-tendermint-1862',
          connection_id: 'connection-1453',
        },
        id: 'connection-13',
        state: 3,
        transferChannel: {
          channelId: 'channel-3',
          counterPartyChannelId: 'channel-208',
          counterPartyPortId: 'transfer',
          ordering: 0,
          portId: 'transfer',
          state: 3,
          version: 'ics20-1',
        },
      },
      'pacific-1': {
        client_id: '07-tendermint-151',
        counterparty: {
          client_id: '07-tendermint-8',
          connection_id: 'connection-2',
        },
        id: 'connection-136',
        state: 3,
        transferChannel: {
          channelId: 'channel-103',
          counterPartyChannelId: 'channel-2',
          counterPartyPortId: 'transfer',
          ordering: 0,
          portId: 'transfer',
          state: 3,
          version: 'ics20-1',
        },
      },
      'phoenix-1': {
        client_id: '07-tendermint-39',
        counterparty: {
          client_id: '07-tendermint-7',
          connection_id: 'connection-10',
        },
        id: 'connection-21',
        state: 3,
        transferChannel: {
          channelId: 'channel-11',
          counterPartyChannelId: 'channel-6',
          counterPartyPortId: 'transfer',
          ordering: 0,
          portId: 'transfer',
          state: 3,
          version: 'ics20-1',
        },
      },
      'pio-mainnet-1': {
        client_id: '07-tendermint-175',
        counterparty: {
          client_id: '07-tendermint-35',
          connection_id: 'connection-12',
        },
        id: 'connection-153',
        state: 3,
        transferChannel: {
          channelId: 'channel-116',
          counterPartyChannelId: 'channel-9',
          counterPartyPortId: 'transfer',
          ordering: 0,
          portId: 'transfer',
          state: 3,
          version: 'ics20-1',
        },
      },
      'pirin-1': {
        client_id: '07-tendermint-205',
        counterparty: {
          client_id: '07-tendermint-17',
          connection_id: 'connection-13',
        },
        id: 'connection-186',
        state: 3,
        transferChannel: {
          channelId: 'channel-143',
          counterPartyChannelId: 'channel-10177',
          counterPartyPortId: 'transfer',
          ordering: 0,
          portId: 'transfer',
          state: 3,
          version: 'ics20-1',
        },
      },
      'pryzm-1': {
        client_id: '07-tendermint-224',
        counterparty: {
          client_id: '07-tendermint-7',
          connection_id: 'connection-7',
        },
        id: 'connection-209',
        state: 3,
        transferChannel: {
          channelId: 'channel-155',
          counterPartyChannelId: 'channel-13',
          counterPartyPortId: 'transfer',
          ordering: 0,
          portId: 'transfer',
          state: 3,
          version: 'ics20-1',
        },
      },
      'secret-4': {
        client_id: '07-tendermint-40',
        counterparty: {
          client_id: '07-tendermint-44',
          connection_id: 'connection-26',
        },
        id: 'connection-22',
        state: 3,
        transferChannel: {
          channelId: 'channel-12',
          counterPartyChannelId: 'channel-20',
          counterPartyPortId: 'transfer',
          ordering: 0,
          portId: 'transfer',
          state: 3,
          version: 'ics20-1',
        },
      },
      'shido_9008-1': {
        client_id: '07-tendermint-210',
        counterparty: {
          client_id: '07-tendermint-1',
          connection_id: 'connection-1',
        },
        id: 'connection-191',
        state: 3,
        transferChannel: {
          channelId: 'channel-148',
          counterPartyChannelId: 'channel-1',
          counterPartyPortId: 'transfer',
          ordering: 0,
          portId: 'transfer',
          state: 3,
          version: 'ics20-1',
        },
      },
      'stride-1': {
        client_id: '07-tendermint-93',
        counterparty: {
          client_id: '07-tendermint-75',
          connection_id: 'connection-60',
        },
        id: 'connection-78',
        state: 3,
        transferChannel: {
          channelId: 'channel-64',
          counterPartyChannelId: 'channel-69',
          counterPartyPortId: 'transfer',
          ordering: 0,
          portId: 'transfer',
          state: 3,
          version: 'ics20-1',
        },
      },
    },
    icqEnabled: false,
    namespace: 'cosmos',
    reference: 'axelar-dojo-1',
    stakingTokens: [
      {
        denom: 'uaxl',
      },
    ],
  },
  noble: {
    bech32Prefix: 'noble',
    chainId: 'noble-1',
    connections: {
      'agoric-3': {
        client_id: '07-tendermint-32',
        counterparty: {
          client_id: '07-tendermint-77',
          connection_id: 'connection-72',
        },
        id: 'connection-38',
        state: 3,
        transferChannel: {
          channelId: 'channel-21',
          counterPartyChannelId: 'channel-62',
          counterPartyPortId: 'transfer',
          ordering: 0,
          portId: 'transfer',
          state: 3,
          version: 'ics20-1',
        },
      },
      'beezee-1': {
        client_id: '07-tendermint-112',
        counterparty: {
          client_id: '07-tendermint-9',
          connection_id: 'connection-3',
        },
        id: 'connection-107',
        state: 3,
        transferChannel: {
          channelId: 'channel-95',
          counterPartyChannelId: 'channel-3',
          counterPartyPortId: 'transfer',
          ordering: 0,
          portId: 'transfer',
          state: 3,
          version: 'ics20-1',
        },
      },
      'core-1': {
        client_id: '07-tendermint-61',
        counterparty: {
          client_id: '07-tendermint-160',
          connection_id: 'connection-198',
        },
        id: 'connection-59',
        state: 3,
        transferChannel: {
          channelId: 'channel-36',
          counterPartyChannelId: 'channel-132',
          counterPartyPortId: 'transfer',
          ordering: 0,
          portId: 'transfer',
          state: 3,
          version: 'ics20-1',
        },
      },
      'coreum-mainnet-1': {
        client_id: '07-tendermint-71',
        counterparty: {
          client_id: '07-tendermint-32',
          connection_id: 'connection-21',
        },
        id: 'connection-72',
        state: 3,
        transferChannel: {
          channelId: 'channel-49',
          counterPartyChannelId: 'channel-19',
          counterPartyPortId: 'transfer',
          ordering: 0,
          portId: 'transfer',
          state: 3,
          version: 'ics20-1',
        },
      },
      'cosmoshub-4': {
        client_id: '07-tendermint-4',
        counterparty: {
          client_id: '07-tendermint-1116',
          connection_id: 'connection-790',
        },
        id: 'connection-12',
        state: 3,
        transferChannel: {
          channelId: 'channel-4',
          counterPartyChannelId: 'channel-536',
          counterPartyPortId: 'transfer',
          ordering: 0,
          portId: 'transfer',
          state: 3,
          version: 'ics20-1',
        },
      },
      'crescent-1': {
        client_id: '07-tendermint-1',
        counterparty: {
          client_id: '07-tendermint-68',
          connection_id: 'connection-63',
        },
        id: 'connection-1',
        state: 3,
        transferChannel: {
          channelId: 'channel-0',
          counterPartyChannelId: 'channel-38',
          counterPartyPortId: 'transfer',
          ordering: 0,
          portId: 'transfer',
          state: 3,
          version: 'ics20-1',
        },
      },
      'dydx-mainnet-1': {
        client_id: '07-tendermint-59',
        counterparty: {
          client_id: '07-tendermint-0',
          connection_id: 'connection-0',
        },
        id: 'connection-57',
        state: 3,
        transferChannel: {
          channelId: 'channel-33',
          counterPartyChannelId: 'channel-0',
          counterPartyPortId: 'transfer',
          ordering: 0,
          portId: 'transfer',
          state: 3,
          version: 'ics20-1',
        },
      },
      'dymension_1100-1': {
        client_id: '07-tendermint-79',
        counterparty: {
          client_id: '07-tendermint-14',
          connection_id: 'connection-7',
        },
        id: 'connection-80',
        state: 3,
        transferChannel: {
          channelId: 'channel-62',
          counterPartyChannelId: 'channel-6',
          counterPartyPortId: 'transfer',
          ordering: 0,
          portId: 'transfer',
          state: 3,
          version: 'ics20-1',
        },
      },
      'evmos_9001-2': {
        client_id: '07-tendermint-12',
        counterparty: {
          client_id: '07-tendermint-106',
          connection_id: 'connection-63',
        },
        id: 'connection-19',
        state: 3,
        transferChannel: {
          channelId: 'channel-7',
          counterPartyChannelId: 'channel-64',
          counterPartyPortId: 'transfer',
          ordering: 0,
          portId: 'transfer',
          state: 3,
          version: 'ics20-1',
        },
      },
      'haqq_11235-1': {
        client_id: '07-tendermint-58',
        counterparty: {
          client_id: '07-tendermint-4',
          connection_id: 'connection-4',
        },
        id: 'connection-56',
        state: 3,
        transferChannel: {
          channelId: 'channel-32',
          counterPartyChannelId: 'channel-4',
          counterPartyPortId: 'transfer',
          ordering: 0,
          portId: 'transfer',
          state: 3,
          version: 'ics20-1',
        },
      },
      'injective-1': {
        client_id: '07-tendermint-57',
        counterparty: {
          client_id: '07-tendermint-212',
          connection_id: 'connection-195',
        },
        id: 'connection-55',
        state: 3,
        transferChannel: {
          channelId: 'channel-31',
          counterPartyChannelId: 'channel-148',
          counterPartyPortId: 'transfer',
          ordering: 0,
          portId: 'transfer',
          state: 3,
          version: 'ics20-1',
        },
      },
      'juno-1': {
        client_id: '07-tendermint-3',
        counterparty: {
          client_id: '07-tendermint-334',
          connection_id: 'connection-322',
        },
        id: 'connection-8',
        state: 3,
        transferChannel: {
          channelId: 'channel-3',
          counterPartyChannelId: 'channel-224',
          counterPartyPortId: 'transfer',
          ordering: 0,
          portId: 'transfer',
          state: 3,
          version: 'ics20-1',
        },
      },
      'kaiyo-1': {
        client_id: '07-tendermint-2',
        counterparty: {
          client_id: '07-tendermint-95',
          connection_id: 'connection-65',
        },
        id: 'connection-4',
        state: 3,
        transferChannel: {
          channelId: 'channel-2',
          counterPartyChannelId: 'channel-62',
          counterPartyPortId: 'transfer',
          ordering: 0,
          portId: 'transfer',
          state: 3,
          version: 'ics20-1',
        },
      },
      'kava_2222-10': {
        client_id: '07-tendermint-107',
        counterparty: {
          client_id: '07-tendermint-172',
          connection_id: 'connection-214',
        },
        id: 'connection-102',
        state: 3,
        transferChannel: {
          channelId: 'channel-88',
          counterPartyChannelId: 'channel-151',
          counterPartyPortId: 'transfer',
          ordering: 0,
          portId: 'transfer',
          state: 3,
          version: 'ics20-1',
        },
      },
      'lava-mainnet-1': {
        client_id: '07-tendermint-120',
        counterparty: {
          client_id: '07-tendermint-11',
          connection_id: 'connection-15',
        },
        id: 'connection-115',
        state: 3,
        transferChannel: {
          channelId: 'channel-105',
          counterPartyChannelId: 'channel-9',
          counterPartyPortId: 'transfer',
          ordering: 0,
          portId: 'transfer',
          state: 3,
          version: 'ics20-1',
        },
      },
      'migaloo-1': {
        client_id: '07-tendermint-19',
        counterparty: {
          client_id: '07-tendermint-113',
          connection_id: 'connection-89',
        },
        id: 'connection-28',
        state: 3,
        transferChannel: {
          channelId: 'channel-14',
          counterPartyChannelId: 'channel-60',
          counterPartyPortId: 'transfer',
          ordering: 0,
          portId: 'transfer',
          state: 3,
          version: 'ics20-1',
        },
      },
      'neutron-1': {
        client_id: '07-tendermint-25',
        counterparty: {
          client_id: '07-tendermint-40',
          connection_id: 'connection-31',
        },
        id: 'connection-34',
        state: 3,
        transferChannel: {
          channelId: 'channel-18',
          counterPartyChannelId: 'channel-30',
          counterPartyPortId: 'transfer',
          ordering: 0,
          portId: 'transfer',
          state: 3,
          version: 'ics20-1',
        },
      },
      'omniflixhub-1': {
        client_id: '07-tendermint-68',
        counterparty: {
          client_id: '07-tendermint-51',
          connection_id: 'connection-49',
        },
        id: 'connection-65',
        state: 3,
        transferChannel: {
          channelId: 'channel-44',
          counterPartyChannelId: 'channel-38',
          counterPartyPortId: 'transfer',
          ordering: 0,
          portId: 'transfer',
          state: 3,
          version: 'ics20-1',
        },
      },
      'osmosis-1': {
        client_id: '07-tendermint-0',
        counterparty: {
          client_id: '07-tendermint-2704',
          connection_id: 'connection-2241',
        },
        id: 'connection-2',
        state: 3,
        transferChannel: {
          channelId: 'channel-1',
          counterPartyChannelId: 'channel-750',
          counterPartyPortId: 'transfer',
          ordering: 0,
          portId: 'transfer',
          state: 3,
          version: 'ics20-1',
        },
      },
      'pacific-1': {
        client_id: '07-tendermint-64',
        counterparty: {
          client_id: '07-tendermint-45',
          connection_id: 'connection-77',
        },
        id: 'connection-61',
        state: 3,
        transferChannel: {
          channelId: 'channel-39',
          counterPartyChannelId: 'channel-45',
          counterPartyPortId: 'transfer',
          ordering: 0,
          portId: 'transfer',
          state: 3,
          version: 'ics20-1',
        },
      },
      'phoenix-1': {
        client_id: '07-tendermint-56',
        counterparty: {
          client_id: '07-tendermint-367',
          connection_id: 'connection-302',
        },
        id: 'connection-54',
        state: 3,
        transferChannel: {
          channelId: 'channel-30',
          counterPartyChannelId: 'channel-253',
          counterPartyPortId: 'transfer',
          ordering: 0,
          portId: 'transfer',
          state: 3,
          version: 'ics20-1',
        },
      },
      'pio-mainnet-1': {
        client_id: '07-tendermint-30',
        counterparty: {
          client_id: '07-tendermint-36',
          connection_id: 'connection-13',
        },
        id: 'connection-37',
        state: 3,
        transferChannel: {
          channelId: 'channel-20',
          counterPartyChannelId: 'channel-10',
          counterPartyPortId: 'transfer',
          ordering: 0,
          portId: 'transfer',
          state: 3,
          version: 'ics20-1',
        },
      },
      'planq_7070-2': {
        client_id: '07-tendermint-103',
        counterparty: {
          client_id: '07-tendermint-567',
          connection_id: 'connection-490',
        },
        id: 'connection-95',
        state: 3,
        transferChannel: {
          channelId: 'channel-82',
          counterPartyChannelId: 'channel-63',
          counterPartyPortId: 'transfer',
          ordering: 0,
          portId: 'transfer',
          state: 3,
          version: 'ics20-1',
        },
      },
      'pryzm-1': {
        client_id: '07-tendermint-100',
        counterparty: {
          client_id: '07-tendermint-5',
          connection_id: 'connection-5',
        },
        id: 'connection-92',
        state: 3,
        transferChannel: {
          channelId: 'channel-79',
          counterPartyChannelId: 'channel-5',
          counterPartyPortId: 'transfer',
          ordering: 0,
          portId: 'transfer',
          state: 3,
          version: 'ics20-1',
        },
      },
      'secret-4': {
        client_id: '07-tendermint-24',
        counterparty: {
          client_id: '07-tendermint-170',
          connection_id: 'connection-127',
        },
        id: 'connection-33',
        state: 3,
        transferChannel: {
          channelId: 'channel-17',
          counterPartyChannelId: 'channel-88',
          counterPartyPortId: 'transfer',
          ordering: 0,
          portId: 'transfer',
          state: 3,
          version: 'ics20-1',
        },
      },
      'shido_9008-1': {
        client_id: '07-tendermint-106',
        counterparty: {
          client_id: '07-tendermint-9',
          connection_id: 'connection-11',
        },
        id: 'connection-99',
        state: 3,
        transferChannel: {
          channelId: 'channel-87',
          counterPartyChannelId: 'channel-5',
          counterPartyPortId: 'transfer',
          ordering: 0,
          portId: 'transfer',
          state: 3,
          version: 'ics20-1',
        },
      },
      'stargaze-1': {
        client_id: '07-tendermint-16',
        counterparty: {
          client_id: '07-tendermint-287',
          connection_id: 'connection-214',
        },
        id: 'connection-25',
        state: 3,
        transferChannel: {
          channelId: 'channel-11',
          counterPartyChannelId: 'channel-204',
          counterPartyPortId: 'transfer',
          ordering: 0,
          portId: 'transfer',
          state: 3,
          version: 'ics20-1',
        },
      },
      'titan_18888-1': {
        client_id: '07-tendermint-114',
        counterparty: {
          client_id: '07-tendermint-1',
          connection_id: 'connection-0',
        },
        id: 'connection-109',
        state: 3,
        transferChannel: {
          channelId: 'channel-99',
          counterPartyChannelId: 'channel-0',
          counterPartyPortId: 'transfer',
          ordering: 0,
          portId: 'transfer',
          state: 3,
          version: 'ics20-1',
        },
      },
      'umee-1': {
        client_id: '07-tendermint-73',
        counterparty: {
          client_id: '07-tendermint-248',
          connection_id: 'connection-210',
        },
        id: 'connection-74',
        state: 3,
        transferChannel: {
          channelId: 'channel-51',
          counterPartyChannelId: 'channel-120',
          counterPartyPortId: 'transfer',
          ordering: 0,
          portId: 'transfer',
          state: 3,
          version: 'ics20-1',
        },
      },
      'vota-ash': {
        client_id: '07-tendermint-111',
        counterparty: {
          client_id: '07-tendermint-23',
          connection_id: 'connection-29',
        },
        id: 'connection-106',
        state: 3,
        transferChannel: {
          channelId: 'channel-94',
          counterPartyChannelId: 'channel-14',
          counterPartyPortId: 'transfer',
          ordering: 0,
          portId: 'transfer',
          state: 3,
          version: 'ics20-1',
        },
      },
    },
    icqEnabled: false,
    namespace: 'cosmos',
    reference: 'noble-1',
  },
};
harden(chainInfoProposal100);

/**
 * Per-instance contract addresses for ymax1 that differ from the base
 * axelar-configs addresses (which correspond to ymax0).
 */
export const instanceOverrides = harden({
  ymax1: {
    Arbitrum: {
      depositFactory: '0x0F0D45A7b641C565799a68aDB41edEf4D6959E4A',
      remoteAccountFactory: '0xaf57110d2d2d4c1CAD294031505bd4A8b0F3966F',
      remoteAccountImplementation: '0xDf90cDf5D0e1ba5640A61615dd242b771e74cfD9',
      remoteAccountRouter: '0xb82BBf2780C4c5BC8f135EE1d4a7e33eF21Ac6b5',
    },
    Avalanche: {
      depositFactory: '0x0F0D45A7b641C565799a68aDB41edEf4D6959E4A',
      remoteAccountFactory: '0xaf57110d2d2d4c1CAD294031505bd4A8b0F3966F',
      remoteAccountImplementation: '0xDf90cDf5D0e1ba5640A61615dd242b771e74cfD9',
      remoteAccountRouter: '0xb82BBf2780C4c5BC8f135EE1d4a7e33eF21Ac6b5',
    },
    Base: {
      depositFactory: '0x0F0D45A7b641C565799a68aDB41edEf4D6959E4A',
      remoteAccountFactory: '0xaf57110d2d2d4c1CAD294031505bd4A8b0F3966F',
      remoteAccountImplementation: '0xDf90cDf5D0e1ba5640A61615dd242b771e74cfD9',
      remoteAccountRouter: '0xb82BBf2780C4c5BC8f135EE1d4a7e33eF21Ac6b5',
    },
    Ethereum: {
      depositFactory: '0x0F0D45A7b641C565799a68aDB41edEf4D6959E4A',
      remoteAccountFactory: '0xaf57110d2d2d4c1CAD294031505bd4A8b0F3966F',
      remoteAccountImplementation: '0xDf90cDf5D0e1ba5640A61615dd242b771e74cfD9',
      remoteAccountRouter: '0xb82BBf2780C4c5BC8f135EE1d4a7e33eF21Ac6b5',
    },
    Optimism: {
      depositFactory: '0x0F0D45A7b641C565799a68aDB41edEf4D6959E4A',
      remoteAccountFactory: '0xaf57110d2d2d4c1CAD294031505bd4A8b0F3966F',
      remoteAccountImplementation: '0xDf90cDf5D0e1ba5640A61615dd242b771e74cfD9',
      remoteAccountRouter: '0xb82BBf2780C4c5BC8f135EE1d4a7e33eF21Ac6b5',
    },
  },
});
