enableScripts: false

nodeLinker: node-modules
enableTransparentWorkspaces: true

nmHoistingLimits: workspaces
# benchmarked default (31s), global (13s), local (7s)
nmMode: hardlinks-local

yarnPath: .yarn/releases/yarn-4.12.0.cjs
