enableScripts: false

nodeLinker: pnpm

# benchmarked default (31s), global (13s), local (7s)
nmMode: hardlinks-local

packageExtensions:
  # correct undeclared deps that pnpm linker strictness requires
  '@endo/eslint-plugin@*':
    dependencies:
      '@typescript-eslint/utils': '^8.33.0'

yarnPath: .yarn/releases/yarn-4.12.0.cjs
