approvedGitRepositories:
# none

enableScripts: false

nmMode: hardlinks-local

nodeLinker: node-modules

# to allow for agoric 'dev' packages;
# assumes Socket Security is sufficient
npmMinimalAgeGate: 0

yarnPath: .yarn/releases/yarn-4.17.0.cjs
