#! /bin/sh
PORT=8000
SOLO_NAME=agoric
SOLO_HOME=${SOLO_HOME-solo/$SOLO_NAME}
ENTRYPOINT=bin/ag-solo
if test "$1" = shell; then
  ENTRYPOINT=/bin/bash
  shift
fi
exec docker run -p127.0.0.1:$PORT:$PORT \
  --volume=ag-solo-state:/usr/src/app/solo \
  -eAG_SOLO_BASEDIR="$SOLO_HOME" \
  --rm -it --entrypoint="$ENTRYPOINT" \
  agoric/cosmic-swingset ${1+"$@"}
