#! /bin/sh
test -t 1 && FLAGS=-t
thisdir=`dirname "$0"`
ABS=`cd "$thisdir" && pwd`
COSSD_PORT=26657
REST_PORT=1317
ENTRY=./sscli
ARGS=


case "$1" in
rest-server)
  # FIXME: Does this actually work?
  FLAGS="-p127.0.0.1:$REST_PORT:$REST_PORT"
  case " $@ " in
  *" --help "*) ;;
  *)
    if test `uname -s 2>/dev/null` = Darwin; then
      # On MacOS, run the tunnel to host.docker.internal:$COSSD_PORT.
      # FIXME: Windows needs the same.
      ENTRY=/ssh-tunnel
      FLAGS="$FLAGS -t --volume=$HOME/.ssh:/root/.ssh" # --volume=$ABS/ssh-tunnel:/ssh-tunnel"
      ARGS=" $USER@host.docker.internal $COSSD_PORT ./sscli"
    fi
    ;;
  esac
  ;;
*)
  FLAGS="--net=host"
  ;;
esac

exec docker run -i --net=host $FLAGS --entrypoint="$ENTRY" \
  --volume=sscli-state:/root/.sscli \
  --rm agoric/cosmic-swingset$ARGS ${1+"$@"}
