export const ACTIVATE_CONNECTION = 'ACTIVATE_CONNECTION';
export const DEACTIVATE_CONNECTION = 'DEACTIVATE_CONNECTION';

export const SERVER_CONNECTED = 'SERVER_CONNECTED';
export const SERVER_DISCONNECTED = 'SERVER_DISCONNECTED';

export const UPDATE_PURSES = 'UPDATE_PURSES';
export const SWAP_PURSES = 'SWAP_PURSES';

export const CHANGE_PURSE = 'CHANGE_PURSE';
export const CHANGE_AMOUNT = 'CHANGE_AMOUNT';

export const CREATE_OFFER = 'CREATE_OFFER';
