export const ACTIVATE_CONNECTION = 'ACTIVATE_CONNECTION';
export const DEACTIVATE_CONNECTION = 'DEACTIVATE_CONNECTION';

export const SERVER_CONNECTED = 'SERVER_CONNECTED';
export const SERVER_DISCONNECTED = 'SERVER_DISCONNECTED';

export const UPDATE_PURSES = 'UPDATE_PURSES';
export const UPDATE_TRANSACTIONS = 'UPDATE_TRANSACTIONS';

export const CONFIRM_TRADE = 'CONFIRM_TRADE';
export const REJECT_TRADE = 'REJECT_TRADE';
