
all: TestChainPair_Agoric_Cosmos_1Val_Hermes TestPacketForwardMiddleware_Agoric_Gaia

TestChainPair_Agoric_Cosmos_1Val_CosmosRly:
	go test -v -run ^TestChainPair_Agoric_Cosmos_1Val_CosmosRly

TestChainPair_Agoric_Cosmos_1Val_Hermes:
	go test -v -run ^TestChainPair_Agoric_Cosmos_1Val_Hermes

TestChainPair_Cosmos_Cosmos_1Val_CosmosRly:
	go test -v -run ^TestChainPair_Cosmos_Cosmos_1Val_CosmosRly

TestChainPair_Cosmos_Cosmos_1Val_Hermes:
	go test -v -run ^TestChainPair_Cosmos_Cosmos_1Val_Hermes

TestChainPair_Cosmos_Agoric_1Val_Hermes:
	go test -v -run ^TestChainPair_Cosmos_Agoric_1Val_Hermes

TestChainPair_Agoric_Agoric_1Val_CosmosRly:
	go test -v -run ^TestChainPair_Agoric_Agoric_1Val_CosmosRly

TestChainPair_Agoric_Agoric_1Val_Hermes:
	go test -v -run ^TestChainPair_Agoric_Agoric_1Val_Hermes

TestChainPair_Agoric_Cosmos_2Val:
	go test -v -run ^TestChainPair_Agoric_Cosmos_2Val

TestPacketForwardMiddleware_AllGaia:
	go test -v -run ^TestPacketForwardMiddleware_AllGaia

TestPacketForwardMiddleware_Agoric_Gaia:
	go test -v -run ^TestPacketForwardMiddleware_Agoric_Gaia