services:
  app:
    image: ghcr.io/agoric/ymax-planner:latest
    # entrypoint: ['/bin/sleep', '864000'] # 24 hours
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - planner_home:/data/portfolio-planner

volumes:
  planner_home:
