export const ACTIVATE_CONNECTION = 'ACTIVATE_CONNECTION';
export const DEACTIVATE_CONNECTION = 'DEACTIVATE_CONNECTION';

export const SERVER_CONNECTED = 'SERVER_CONNECTED';
export const SERVER_DISCONNECTED = 'SERVER_DISCONNECTED';

export const UPDATE_PURSES = 'UPDATE_PURSES';
export const UPDATE_INBOX = 'UPDATE_INBOX';

export const REJECT_OFFER = 'REJECT_OFFER';
export const CONFIRM_OFFER = 'CONFIRM_OFFER';
export const CANCEL_OFFER = 'CANCEL_OFFER';
