name: agoric-multichain-testing
version: v1.7

chains:
  - id: agoriclocal
    name: agoric
    image: ghcr.io/agoric/agoric-sdk:dev
    numValidators: 1
    env:
      - name: DEBUG
        value: SwingSet:vat,SwingSet:ls
      # CONFIG_FILE env is for scripts/update-config.sh
      - name: CONFIG_FILE
        value: 'config.xcs-swap-anything.yaml'
      - name: SNAPSHOT_URL
        value: https://storage.googleapis.com/agoric-snapshots-public/starship-agoric/agoric-snapshot.tar.gz
    genesis:
      app_state:
        staking:
          params:
            unbonding_time: '2m'
        swingset:
          params:
            bootstrap_vat_config: '@agoric/vm-config/decentral-itest-orchestration-config.json'
    scripts:
      updateConfig:
        file: scripts/update-config.sh
    faucet:
      enabled: true
      type: starship
    ports:
      rest: 1317
      rpc: 26657
      exposer: 38087
      grpc: 9090
      faucet: 8082
    resources:
      cpu: 1
      memory: 4Gi
  - id: osmosislocal
    name: osmosis
    image: ghcr.io/cosmology-tech/starship/osmosis:v28.0.0
    numValidators: 1
    genesis:
      app_state:
        feemarket:
          params:
            min_base_gas_price: '0.000000000000000000'
            enabled: true
            fee_denom: 'uosmo'
        globalfee:
          params:
            minimum_gas_prices:
              - denom: 'uosmo'
                amount: '0'
        staking:
          params:
            unbonding_time: '2m'
        interchainaccounts:
          host_genesis_state:
            params:
              host_enabled: true
              allow_messages: ['*']
        interchainquery:
          host_port: 'icqhost'
          params:
            host_enabled: true
            allow_queries:
              - /cosmos.bank.v1beta1.Query/Balance
              - /cosmos.bank.v1beta1.Query/AllBalances
    faucet:
      enabled: true
      type: starship
    ports:
      rest: 1315
      rpc: 26655
      grpc: 9093
      faucet: 8084
    resources:
      cpu: 1
      memory: 1Gi
  - id: cosmoshublocal
    name: cosmoshub
    image: ghcr.io/hyperweb-io/starship/gaia:v21.0.1
    numValidators: 1
    genesis:
      app_state:
        feemarket:
          params:
            min_base_gas_price: '0.000000000000000000'
            enabled: true
            fee_denom: 'uatom'
        globalfee:
          params:
            minimum_gas_prices:
              - denom: 'uatom'
                amount: '0'
        staking:
          params:
            unbonding_time: '2m'
        interchainaccounts:
          host_genesis_state:
            params:
              host_enabled: true
              allow_messages: ['*']
    faucet:
      enabled: true
      type: starship
    ports:
      rest: 1314
      rpc: 26654
      grpc: 9092
      faucet: 8083
    resources:
      cpu: 1
      memory: 1Gi

relayers:
  - name: osmosis-cosmoshub
    type: hermes
    # image: ghcr.io/cosmology-tech/starship/hermes:1.10.5
    replicas: 1
    chains:
      - osmosislocal
      - cosmoshublocal
  - name: agoric-osmosis
    type: hermes
    # image: ghcr.io/cosmology-tech/starship/hermes:1.10.5
    replicas: 1
    chains:
      - agoriclocal
      - osmosislocal
    config:
      global:
        log_level: 'debug'
      telemetry:
        enabled: true
  - name: agoric-cosmoshub
    type: hermes
    # image: ghcr.io/cosmology-tech/starship/hermes:1.10.5
    replicas: 1
    chains:
      - agoriclocal
      - cosmoshublocal

explorer:
  enabled: false

registry:
  enabled: true
  ports:
    rest: 8081
