name: agoric-multichain-testing-ymax
version: v1.7

chains:
  - id: agoriclocal
    name: agoric
    image: ghcr.io/agoric/agoric-sdk:dev
    numValidators: 1
    env:
      - name: DEBUG
        value: SwingSet:vat,SwingSet:ls
    genesis:
      app_state:
        staking:
          params:
            unbonding_time: '2m'
        swingset:
          params:
            bootstrap_vat_config: '@agoric/vm-config/decentral-itest-orchestration-config.json'
    scripts:
      updateConfig:
        file: scripts/update-config.sh
    faucet:
      enabled: true
      type: starship
    ports:
      rest: 1317
      rpc: 26657
      exposer: 38087
      grpc: 9090
      faucet: 8082
    resources:
      cpu: 1
      memory: 4Gi
  - id: noblelocal
    name: noble
    image: ghcr.io/agoric/noble:v10.0.0
    numValidators: 1
    balances:
      # USDN whale
      # energy bar acquire twist stick uncle echo chicken track dad position unveil define addict else matrix sauce onion tornado breeze grape basket gauge soon
      - address: noble16fskzhlguwkq35f5hmvnxg6urug46fhmn9frwu
        amount: 100000000000000uusdn,100000000000000uusdc
    genesis:
      app_state:
        staking:
          params:
            unbonding_time: '2m'
        interchainaccounts:
          host_genesis_state:
            params:
              host_enabled: true
              allow_messages: ['*']
    scripts:
      updateGenesis:
        # We can modify this script as per need for ymax
        file: scripts/noble-v10-update-genesis.sh
    faucet:
      enabled: true
      type: starship
    ports:
      rest: 1314
      rpc: 26654
      grpc: 9092
      faucet: 8083
    resources:
      cpu: 1
      memory: 1Gi

relayers:
  - name: agoric-noble
    type: hermes
    replicas: 1
    chains:
      - agoriclocal
      - noblelocal

explorer:
  enabled: false

registry:
  enabled: true
  ports:
    rest: 8081
