/**
 * @import {
 * Bundle,
 * BundleCap,
 * BundleFormat,
 * BundleID,
 * BundleRef,
 * BundleSpec,
 * DeviceInvocation,
 * DeviceInvocationResult,
 * DeviceInvocationResultError,
 * DeviceInvocationResultOk,
 * EndoZipBase64Bundle,
 * GetExportBundle,
 * KernelDeliveryBringOutYourDead,
 * KernelDeliveryChangeVatOptions,
 * KernelDeliveryDropExports,
 * KernelDeliveryMessage,
 * KernelDeliveryNotify,
 * KernelDeliveryObject,
 * KernelDeliveryOneNotify,
 * KernelDeliveryRetireExports,
 * KernelDeliveryRetireImports,
 * KernelDeliveryStartVat,
 * KernelKeeper,
 * KernelOneResolution,
 * KernelOptions,
 * KernelSlog,
 * KernelSyscallDropImports,
 * KernelSyscallExit,
 * KernelSyscallInvoke,
 * KernelSyscallObject,
 * KernelSyscallResolve,
 * KernelSyscallResult,
 * KernelSyscallResultError,
 * KernelSyscallResultOk,
 * KernelSyscallRetireExports,
 * KernelSyscallRetireImports,
 * KernelSyscallSend,
 * KernelSyscallSubscribe,
 * KernelSyscallVatstoreDelete,
 * KernelSyscallVatstoreGet,
 * KernelSyscallVatstoreGetNextKey,
 * KernelSyscallVatstoreSet,
 * ManagerType,
 * Message,
 * MeteringVatPowers,
 * NestedEvaluateBundle,
 * PolicyInput,
 * PolicyInputCrankComplete,
 * PolicyInputCrankFailed,
 * PolicyInputCreateVat,
 * PolicyInputNone,
 * PolicyOutput,
 * ResolutionPolicy,
 * RunPolicy,
 * SlogFinishDelivery,
 * SlogFinishSyscall,
 * SnapshotResult,
 * SnapStore,
 * SourceOfBundle,
 * SourceSpec,
 * StaticVatPowers,
 * SwingSetCapData,
 * SwingSetConfig,
 * SwingSetConfigDescriptor,
 * SwingSetConfigProperties,
 * SwingSetKernelConfig,
 * TerminationVatPowers,
 * VatKeeper,
 * VatPowers,
 * VatSlog,
 * VatStats,
 * WaitUntilQuiescent,
 * XSnap,
 * } from './types-external.js')
 */

/**
 * @import {
 * KVStore,
 * TranscriptStore,
 * SwingStore,
 * SwingStoreKernelStorage,
 * SwingStoreHostStorage,
 * } from '@agoric/swing-store'
 */

// XXX miscellaneous types that downstream code expects to be ambient
/**
 * @import {ERef} from '@endo/far';
 * @import {PromiseKit, PromiseRecord} from '@endo/promise-kit';
 * @import {StorageNode} from '@agoric/internal/src/lib-chainStorage.js';
 * @import {EachTopic, IterableEachTopic, IterationObserver, LatestTopic, Marshaller, Notifier, NotifierRecord, PublicationRecord, Publisher, PublishKit, StoredPublishKit, StoredSubscriber, StoredSubscription, Subscriber, Subscription, SubscriptionRecord, UpdateRecord, VStorageKey} from '@agoric/notifier';
 */
