name: Agoric SDK restore Node.js build
description: 'Set up Node.js environment and restore cached built files'

inputs:
  node-version:
    description: 'The version of Node.js to use'
    required: true

runs:
  using: composite
  steps:
    - name: set default environment variables
      run: echo ESM_DISABLE_CACHE=true >> $GITHUB_ENV
      shell: bash
    - uses: actions/checkout@v2
      with:
        clean: 'false'
        submodules: 'true'
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ inputs.node-version }}
    - uses: kenchan0130/actions-system-info@master
      id: system-info
    - name: restore built files
      id: built
      uses: actions/cache@v1
      with:
        path: .
        key: ${{ runner.os }}-${{ runner.arch }}-${{ steps.system-info.outputs.release }}-node-${{ inputs.node-version }}-built-${{ github.sha }}
    - name: yarn install --frozen-lockfile
      run: yarn install --frozen-lockfile
      shell: bash
      if: steps.built.outputs.cache-hit != 'true'
    - name: yarn build
      run: yarn build
      shell: bash
      if: steps.built.outputs.cache-hit != 'true'
