---
- hosts: '{{ service }}'
  user: root
  #any_errors_fatal: true
  gather_facts: yes
  strategy: free
  vars:
    - service: ag-chain-cosmos
    - APPDIR: "{{lookup('pipe', 'pwd')}}/../.."
  roles:
    - stop
    - copy
    - unsafe_reset
    - start
