#! /bin/sh
PORT=26657
TTY=-i
IMAGE=agoric/cosmic-swingset
test -t 0 && test -t 1 && TTY=-it
case "$1" in
--pull)
  shift
  docker pull "$IMAGE"
  ;;
esac

exec docker run -p127.0.0.1:$PORT:$PORT \
  --volume=ag-chain-cosmos-state:/root/.ag-chain-cosmos \
  --rm $TTY \
  "$IMAGE" ${1+"$@"}
