#! /bin/sh
PORT=8000
SOLO_NAME=${SOLO_NAME-agoric}
SOLO_HOME=${SOLO_HOME-$SOLO_NAME}
IMAGE=agoric/cosmic-swingset-solo
FLAGS=
case "$1" in
--pull)
  shift
  docker pull "$IMAGE"
  ;;
esac

if test "$1" = shell; then
  FLAGS=--entrypoint=/bin/bash
  shift
fi
exec docker run -p127.0.0.1:$PORT:$PORT \
  --volume=ag-solo-state:/usr/src/app/solo \
  -eAG_SOLO_BASEDIR="$SOLO_HOME" \
  --rm -it $FLAGS \
  "$IMAGE" ${1+"$@"}
