// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: agoric/vbank/msgs.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	types "github.com/cosmos/cosmos-sdk/x/bank/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgSetDenomMetaData represents a message to set the metadata for a denom.
type MsgSetDenomMetaData struct {
	// authority is the address that controls the module (defaults to x/gov unless overwritten).
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	// metadata is the bank denom metadata to set.
	Metadata types.Metadata `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata"`
}

func (m *MsgSetDenomMetaData) Reset()         { *m = MsgSetDenomMetaData{} }
func (m *MsgSetDenomMetaData) String() string { return proto.CompactTextString(m) }
func (*MsgSetDenomMetaData) ProtoMessage()    {}
func (*MsgSetDenomMetaData) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f9d0954f3583404, []int{0}
}
func (m *MsgSetDenomMetaData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSetDenomMetaData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSetDenomMetaData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSetDenomMetaData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSetDenomMetaData.Merge(m, src)
}
func (m *MsgSetDenomMetaData) XXX_Size() int {
	return m.Size()
}
func (m *MsgSetDenomMetaData) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSetDenomMetaData.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSetDenomMetaData proto.InternalMessageInfo

func (m *MsgSetDenomMetaData) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgSetDenomMetaData) GetMetadata() types.Metadata {
	if m != nil {
		return m.Metadata
	}
	return types.Metadata{}
}

// MsgSetDenomMetaDataResponse is the response type for the Msg/SetDenomMetaData RPC method.
type MsgSetDenomMetaDataResponse struct {
}

func (m *MsgSetDenomMetaDataResponse) Reset()         { *m = MsgSetDenomMetaDataResponse{} }
func (m *MsgSetDenomMetaDataResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSetDenomMetaDataResponse) ProtoMessage()    {}
func (*MsgSetDenomMetaDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f9d0954f3583404, []int{1}
}
func (m *MsgSetDenomMetaDataResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSetDenomMetaDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSetDenomMetaDataResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSetDenomMetaDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSetDenomMetaDataResponse.Merge(m, src)
}
func (m *MsgSetDenomMetaDataResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSetDenomMetaDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSetDenomMetaDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSetDenomMetaDataResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgSetDenomMetaData)(nil), "agoric.vbank.MsgSetDenomMetaData")
	proto.RegisterType((*MsgSetDenomMetaDataResponse)(nil), "agoric.vbank.MsgSetDenomMetaDataResponse")
}

func init() { proto.RegisterFile("agoric/vbank/msgs.proto", fileDescriptor_4f9d0954f3583404) }

var fileDescriptor_4f9d0954f3583404 = []byte{
	// 370 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xbf, 0x4f, 0xc2, 0x40,
	0x14, 0xc7, 0x7b, 0xfe, 0x8a, 0x54, 0x07, 0xad, 0x24, 0x40, 0x0d, 0x15, 0x99, 0x90, 0x48, 0x2f,
	0x60, 0x62, 0x8c, 0x8b, 0x81, 0xb0, 0x76, 0x29, 0x9b, 0x8b, 0x5e, 0xe9, 0xe5, 0x68, 0xb0, 0x77,
	0xa4, 0x77, 0x10, 0xd9, 0x8c, 0xa3, 0x93, 0x7f, 0x0a, 0x83, 0xa3, 0x7f, 0x00, 0x23, 0x71, 0x72,
	0x32, 0x06, 0x06, 0xfe, 0x0d, 0xc3, 0xdd, 0x29, 0x26, 0x92, 0xb8, 0xb4, 0x7d, 0xef, 0xf3, 0x7d,
	0xdf, 0xbe, 0xbb, 0xf7, 0xcc, 0x0c, 0x22, 0x2c, 0x89, 0xda, 0x70, 0x10, 0x20, 0xda, 0x85, 0x31,
	0x27, 0xdc, 0xed, 0x25, 0x4c, 0x30, 0x6b, 0x57, 0x01, 0x57, 0x02, 0x7b, 0x1f, 0xc5, 0x11, 0x65,
	0x50, 0x3e, 0x95, 0xc0, 0xce, 0xb4, 0x19, 0x8f, 0x19, 0x5f, 0xd4, 0xc0, 0x41, 0x75, 0xf1, 0xd2,
	0xc0, 0xd1, 0x40, 0x3a, 0x0e, 0xaa, 0x01, 0x16, 0xa8, 0x2a, 0x03, 0xcd, 0x73, 0x8a, 0xdf, 0xc8,
	0x08, 0xaa, 0x40, 0xa3, 0x34, 0x61, 0x84, 0xa9, 0xfc, 0xe2, 0x4b, 0x65, 0x8b, 0xaf, 0xc0, 0x3c,
	0xf0, 0x38, 0x69, 0x61, 0xd1, 0xc4, 0x94, 0xc5, 0x1e, 0x16, 0xa8, 0x89, 0x04, 0xb2, 0xce, 0xcd,
	0x14, 0xea, 0x8b, 0x0e, 0x4b, 0x22, 0x31, 0xcc, 0x82, 0x02, 0x28, 0xa5, 0x1a, 0xd9, 0xb7, 0x97,
	0x4a, 0x5a, 0x5b, 0xd6, 0xc3, 0x30, 0xc1, 0x9c, 0xb7, 0x44, 0x12, 0x51, 0xe2, 0x2f, 0xa5, 0xd6,
	0x95, 0xb9, 0x1d, 0x63, 0x81, 0x42, 0x24, 0x50, 0x76, 0xad, 0x00, 0x4a, 0x3b, 0xb5, 0xbc, 0xab,
	0x6b, 0x64, 0x9b, 0xba, 0x67, 0xd7, 0xd3, 0xa2, 0xc6, 0xc6, 0xf8, 0xe3, 0xc8, 0xf0, 0x7f, 0x8a,
	0x2e, 0x4f, 0x1f, 0xe7, 0xa3, 0xf2, 0xd2, 0xf0, 0x69, 0x3e, 0x2a, 0xe7, 0xd4, 0x05, 0xae, 0x68,
	0xb3, 0x98, 0x37, 0x0f, 0x57, 0xa4, 0x7d, 0xcc, 0x7b, 0x8c, 0x72, 0x5c, 0xa3, 0xe6, 0xba, 0xc7,
	0x89, 0x75, 0x6b, 0xee, 0xfd, 0x39, 0xe0, 0xb1, 0xfb, 0x7b, 0x08, 0xee, 0x0a, 0x17, 0xfb, 0xe4,
	0x5f, 0xc9, 0xf7, 0x8f, 0xec, 0xcd, 0x87, 0xf9, 0xa8, 0x0c, 0x1a, 0xfe, 0x78, 0xea, 0x80, 0xc9,
	0xd4, 0x01, 0x9f, 0x53, 0x07, 0x3c, 0xcf, 0x1c, 0x63, 0x32, 0x73, 0x8c, 0xf7, 0x99, 0x63, 0x5c,
	0x5f, 0x90, 0x48, 0x74, 0xfa, 0x81, 0xdb, 0x66, 0x31, 0xac, 0xab, 0xb5, 0x50, 0xe6, 0x15, 0x1e,
	0x76, 0x21, 0x61, 0x77, 0x88, 0x12, 0x3d, 0x2f, 0x78, 0xaf, 0x37, 0x46, 0x0c, 0x7b, 0x98, 0x07,
	0x5b, 0x72, 0x50, 0x67, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xc9, 0x2f, 0x97, 0x97, 0x4e, 0x02,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// SetDenomMetaData defines a governance operation for setting the metadata for a denom.
	// The authority is defined in the keeper.
	SetDenomMetaData(ctx context.Context, in *MsgSetDenomMetaData, opts ...grpc.CallOption) (*MsgSetDenomMetaDataResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) SetDenomMetaData(ctx context.Context, in *MsgSetDenomMetaData, opts ...grpc.CallOption) (*MsgSetDenomMetaDataResponse, error) {
	out := new(MsgSetDenomMetaDataResponse)
	err := c.cc.Invoke(ctx, "/agoric.vbank.Msg/SetDenomMetaData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// SetDenomMetaData defines a governance operation for setting the metadata for a denom.
	// The authority is defined in the keeper.
	SetDenomMetaData(context.Context, *MsgSetDenomMetaData) (*MsgSetDenomMetaDataResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) SetDenomMetaData(ctx context.Context, req *MsgSetDenomMetaData) (*MsgSetDenomMetaDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetDenomMetaData not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_SetDenomMetaData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSetDenomMetaData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SetDenomMetaData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agoric.vbank.Msg/SetDenomMetaData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SetDenomMetaData(ctx, req.(*MsgSetDenomMetaData))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "agoric.vbank.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetDenomMetaData",
			Handler:    _Msg_SetDenomMetaData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agoric/vbank/msgs.proto",
}

func (m *MsgSetDenomMetaData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSetDenomMetaData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSetDenomMetaData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Metadata.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintMsgs(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintMsgs(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSetDenomMetaDataResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSetDenomMetaDataResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSetDenomMetaDataResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintMsgs(dAtA []byte, offset int, v uint64) int {
	offset -= sovMsgs(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgSetDenomMetaData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovMsgs(uint64(l))
	}
	l = m.Metadata.Size()
	n += 1 + l + sovMsgs(uint64(l))
	return n
}

func (m *MsgSetDenomMetaDataResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovMsgs(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMsgs(x uint64) (n int) {
	return sovMsgs(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgSetDenomMetaData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsgs
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSetDenomMetaData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSetDenomMetaData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsgs
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgs
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Metadata", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsgs
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMsgs
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Metadata.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMsgs(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMsgs
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSetDenomMetaDataResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsgs
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSetDenomMetaDataResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSetDenomMetaDataResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipMsgs(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMsgs
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMsgs(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMsgs
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMsgs
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMsgs
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMsgs
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMsgs
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMsgs
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMsgs        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMsgs          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMsgs = fmt.Errorf("proto: unexpected end of group")
)
