description: 'Notify on actions status'

inputs:
  webhook:
    description: 'Slack webhook URL'
    required: true

name: Notify Github Actions status

runs:
  steps:
    - id: slack
      name: Send GitHub trigger payload
      uses: slackapi/slack-github-action@v3.0.3
      with:
        webhook: ${{ inputs.webhook }}
        webhook-type: incoming-webhook
        payload: |
          {
            "text": "Job ${{ github.job }} in workflow ${{ github.workflow }} of ${{ github.repository }} status ${{ job.status }}\nDetails at ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
            "username": "GitHub"
          }

  using: composite
