#! /usr/bin/env node
console.log('Starting Node');
console.log('Setting Node timer');
let i = 0;
setInterval(() => {
    console.log('Node is alive', ++i);
}, 1000);
const coss = require('bindings')('coss.node');
console.log('Have COSS', coss);

const instance = coss.start((port, str) => {
    const action = JSON.parse(str);
    switch (action.type) {
    case 'SET_NAME':
        action.value = action.value.toUpperCase();
        return JSON.stringify(action);
    }
    return JSON.stringify({type: "ERROR", value: `Unknown action.type ${action.type}`});
}, process.argv.slice(1));

console.log('Got from COSS', coss.send(instance, "Hello from node proper!"));
