name: 'Daily Test Coverage Improver - Coverage Steps'
description: 'Build the repo, run tests with coverage, generate combined report, and upload as artifact'

# This composite action:
#   1. Builds all packages
#   2. Runs test:c8 across all packages, collecting V8 coverage into coverage/tmp
#   3. Generates an HTML coverage report in coverage/html
#   4. Uploads the coverage/ directory as a GitHub Actions artifact named "coverage"
#
# Prerequisites: The runner must have Node.js, Yarn, and repo dependencies already installed
# (e.g. via .github/actions/restore-node).
#
# Coverage report location: coverage/html/index.html (HTML) and coverage/tmp (raw V8 JSON)
# Log file: coverage-steps.log (appended by each step)

runs:
  using: composite
  steps:
    - name: Build all packages
      shell: bash
      run: |
        echo "=== Step: Build all packages ===" | tee -a coverage-steps.log
        yarn build 2>&1 | tee -a coverage-steps.log
        echo "Build exit code: $?" | tee -a coverage-steps.log

    - name: Prepare coverage output directories
      shell: bash
      run: |
        echo "=== Step: Prepare coverage directories ===" | tee -a coverage-steps.log
        # NODE_V8_COVERAGE must point to a directory where Node writes raw V8 coverage JSON files.
        # C8_OPTIONS=--clean=false prevents each package from wiping previous coverage,
        # allowing accumulation of coverage across all packages.
        export NODE_V8_COVERAGE="$PWD/coverage/tmp"
        rm -rf "$NODE_V8_COVERAGE"
        mkdir -p "$NODE_V8_COVERAGE"
        echo "NODE_V8_COVERAGE=$NODE_V8_COVERAGE" | tee -a coverage-steps.log
        echo "Directories prepared." | tee -a coverage-steps.log

    - name: Run tests with coverage across all packages
      shell: bash
      env:
        # Raw V8 coverage written here; accumulated across packages
        NODE_V8_COVERAGE: ${{ github.workspace }}/coverage/tmp
        # Prevent c8 from clearing previous coverage data between packages
        C8_OPTIONS: '--clean=false'
        # Increase heap size for large packages
        NODE_OPTIONS: '--max-old-space-size=8192'
      run: |
        echo "=== Step: Run tests with coverage ===" | tee -a coverage-steps.log
        # Ensure coverage tmp dir exists (may have been cleaned between steps)
        mkdir -p "$NODE_V8_COVERAGE"
        # Run test:c8 for every package; --no-bail continues even if a package fails
        yarn lerna run test:c8 --no-bail 2>&1 | tee -a coverage-steps.log
        echo "Test run exit code: $?" | tee -a coverage-steps.log

    - name: Generate combined HTML coverage report
      shell: bash
      run: |
        echo "=== Step: Generate combined coverage report ===" | tee -a coverage-steps.log
        # --all ensures source files with zero coverage are included
        # --include restricts to the packages' src/ and tools/ directories
        # --reports-dir sets where the HTML report is written (coverage/html/index.html)
        yarn c8 report \
          --all \
          --include 'packages/*/{src,tools}/**' \
          --reporter=html-spa \
          --reporter=text-summary \
          --reports-dir=coverage/html \
          --temp-dir=coverage/tmp \
          2>&1 | tee -a coverage-steps.log
        echo "Coverage report generation exit code: $?" | tee -a coverage-steps.log

    - name: Copy log into coverage directory for artifact
      shell: bash
      run: |
        echo "=== Step: Finalize artifact ===" | tee -a coverage-steps.log
        cp coverage-steps.log coverage/coverage-steps.log || true

    - name: Upload coverage artifact
      uses: actions/upload-artifact@v4
      with:
        # Artifact name expected by downstream jobs
        name: coverage
        path: coverage/
        retention-days: 14
