name: Agoric SDK restore Golang build
description: 'Set up Golang environment and restore cached built files'

inputs:
  go-version:
    description: 'The version of Go to use'
    required: true
  cache-key:
    description: pkg/mod cache key
    required: false
    type: string
    default: latest

runs:
  using: composite
  steps:
    - name: set default environment variables
      run: echo GOPATH="$HOME/go" >> $GITHUB_ENV
      shell: bash
    - uses: actions/checkout@v2
      with:
        clean: 'false'
        submodules: 'true'
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ inputs.go-version }}
    - name: cache Go modules
      id: cache
      uses: actions/cache@v1
      with:
        path: ${{ env.GOPATH }}/pkg/mod
        key: ${{ runner.os }}-${{ runner.arch }}-${{ inputs.cache-key }}-go-built-${{ inputs.go-version }}-${{ hashFiles('go.sum') }}
        restore-keys: |
          ${{ runner.os }}-${{ runner.arch }}-${{ inputs.cache-key }}-go-built-${{ inputs.go-version }}-
          ${{ runner.os }}-${{ runner.arch }}-${{ inputs.cache-key }}-go-built-
    - name: go mod download
      run: go mod download
      shell: bash
      if: steps.cache.outputs.cache-hit != 'true'
