name: Agoric SDK restore Golang build
description: 'Set up Golang environment and restore cached built files'

inputs:
  go-version:
    description: 'The version of Go to use'
    required: true
  path:
    description: 'The relative path to the agoric-sdk directory'
    required: false
    default: '.'

runs:
  using: composite
  steps:
    - name: set default environment variables
      run: echo GOPATH="$HOME/go" >> $GITHUB_ENV
      shell: bash
    - uses: actions/checkout@v4
      with:
        path: ${{ inputs.path }}
        clean: 'false'
        submodules: 'true'
    - uses: actions/setup-go@v5
      with:
        cache-dependency-path: ${{ inputs.path }}/golang/cosmos/go.sum
        go-version: ${{ inputs.go-version }}
    - name: go mod download
      working-directory: ${{ inputs.path }}/golang/cosmos
      run: go mod download
      shell: bash
