#!/usr/bin/env node
/* eslint-env node */
const { spawnSync } = require('node:child_process');
const path = require('node:path');
const assert = require('node:assert/strict');
const process = require('node:process');
const fsp = require('node:fs/promises');
const telescope = require('@hyperweb/telescope').default;
const telescopeVersion = require('@hyperweb/telescope/package.json').version;
const rimraf = require('rimraf').rimrafSync;
const {
  getBaseTelescopeOptions,
} = require('../../cosmic-proto/tools/telescope-options.cjs');
const {
  applyTelescopeFixes,
  detectGnuSed,
  fixTypeImportForVerbatim,
} = require('../../cosmic-proto/tools/telescope-cleanup.cjs');

const protoDirs = [path.join(__dirname, '/../../cosmic-proto/proto')];
const outPath = path.join(__dirname, '../src/codegen');
rimraf(outPath);

/**
 * Replace non-RPC generated modules with pass-through re-exports from cosmic-proto.
 *
 * @param {string} directory
 * @returns {Promise<string[]>}
 */
const dedupeCodegenSupportModules = async directory => {
  const header = `//@ts-nocheck
/**
 * This file and any referenced files were automatically generated by @hyperweb/telescope@${telescopeVersion}
 * DO NOT MODIFY BY HAND. Instead, download the latest proto files for your chain
 * and run the transpile command or npm scripts command that is used to regenerate this bundle.
 */
`;

  /** @type {string[]} */
  const changed = [];

  /**
   * @param {string} dirPath
   */
  const walk = async dirPath => {
    const entries = await fsp.readdir(dirPath, { withFileTypes: true });
    for (const entry of entries) {
      const fullPath = path.join(dirPath, entry.name);
      if (entry.isDirectory()) {
        // eslint-disable-next-line no-await-in-loop
        await walk(fullPath);
        continue;
      }
      if (!entry.isFile() || !entry.name.endsWith('.ts')) {
        continue;
      }

      const relativePath = path
        .relative(directory, fullPath)
        .replaceAll('\\', '/');
      if (
        relativePath === 'index.ts' ||
        entry.name === 'bundle.ts' ||
        entry.name.includes('.rpc.') ||
        /^(rpc\.query|rpc\.tx)\.ts$/.test(entry.name)
      ) {
        continue;
      }

      const modulePath = relativePath.replace(/\.ts$/, '.js');
      const source = `${header}
export * from '@agoric/cosmic-proto/codegen/${modulePath}';
`;
      // eslint-disable-next-line no-await-in-loop
      await fsp.writeFile(fullPath, source);
      changed.push(fullPath);
    }
  };

  await walk(directory);
  return changed;
};

const options = getBaseTelescopeOptions();
options.rpcClients = { ...options.rpcClients, enabled: true };
options.stargateClients = { enabled: true };

// XXX copied from cosmic-proto's codegen
telescope({
  protoDirs,
  outPath,
  options,
})
  .then(async () => {
    console.log('🔨 code generated by Telescope');

    // for all files under codegen/ replace "import { JsonSafe" with "import type { JsonSafe"
    const gnuSed = detectGnuSed();
    fixTypeImportForVerbatim('./src/codegen', gnuSed);
    console.log('🔧 type keyword added');

    const prettierResult = spawnSync(
      'yarn',
      ['run', '--top-level', 'prettier', '--write', 'src/codegen'],
      {
        cwd: path.join(__dirname, '..'),
        stdio: 'inherit',
      },
    );
    assert.equal(prettierResult.status, 0);
    console.log('💅 code formatted by Prettier');

    const cleanedFiles = await applyTelescopeFixes({
      outPath,
      includeHelperCleanups: false,
    });
    const dedupedFiles = await dedupeCodegenSupportModules(outPath);
    const postProcessFiles = [...new Set([...cleanedFiles, ...dedupedFiles])];
    if (postProcessFiles.length > 0) {
      const prettierHelpersResult = spawnSync(
        'yarn',
        [
          'run',
          '--top-level',
          'prettier',
          '--write',
          ...postProcessFiles.map(file =>
            path.relative(path.join(__dirname, '..'), file),
          ),
        ],
        {
          cwd: path.join(__dirname, '..'),
          stdio: 'inherit',
        },
      );
      assert.equal(prettierHelpersResult.status, 0);
    }
    console.log('🧹 cleaned generated helper compatibility imports');

    console.log('ℹ️ `yarn build && yarn test` to test it.');
  })
  .catch(e => {
    console.error(e);
    process.exit(1);
  });
