@startuml VaultFactory
header Agoric Systems Operating Company.
footer v0.0.1
title VaultFactory

skinparam componentStyle rectangle
skinparam defaultTextAlignment center


actor "VaultFactoryCreator aka Governance" as vfc

actor Borrower

node AdjustBalancesInvitation
node "CloseVaultInvitation"

node "Vat" {
    node VaultFactory {
        node "publicAPI" {
            circle getCollateralManager
            circle getDebtIssuer
            circle getSubscription
            circle getPublicTopics
            circle getElectorateSubscription
            circle getGovernedParams
            circle getInvitationAmount
        }
        node "creatorFacet" {
            circle makeAddTypeInvitation
        }
    }
    node "Vault" {
        circle makeCloseInvitation
        makeCloseInvitation -u-> CloseVaultInvitation
        circle makeAdjustBalancesInvitation
        makeAdjustBalancesInvitation -u-> AdjustBalancesInvitation
        circle getCollateralAmount
        circle getCurrentDebt
    }
}
Borrower -> makeVaultInvitation: open vault and transfer collateral
makeVaultInvitation -d-> Vault
Borrower -u-> getPayout: retrieve any proceeds
Borrower -u-> getPayouts: retrieve any proceeds
Borrower -> AdjustBalancesInvitation: add or remove collateral or \nincrease or decrease the loan balance
Borrower -l-> CloseVaultInvitation: close loan and withdraw \nany remaining collateral
vfc -d-> makeAddTypeInvitation
Borrower -d-> getCurrentDebt: how much do I owe
Borrower -d-> getCollateralAmount: how much did I \ndeposit as collateral

@enduml
