catalogs:
  endo:
    '@endo/base64': ^1.0.12
    '@endo/bundle-source': ^4.1.2
    '@endo/captp': ^4.4.8
    '@endo/check-bundle': ^1.0.17
    '@endo/common': ^1.2.13
    '@endo/compartment-mapper': ^1.6.3
    '@endo/env-options': ^1.1.11
    '@endo/errors': ^1.2.13
    '@endo/eslint-plugin': ^2.4.0
    '@endo/eventual-send': ^1.3.4
    '@endo/exo': ^1.5.12
    '@endo/far': ^1.1.14
    '@endo/import-bundle': ^1.5.2
    '@endo/init': ^1.1.12
    '@endo/lockdown': ^1.0.18
    '@endo/marshal': ^1.8.0
    '@endo/nat': ^5.1.3
    '@endo/netstring': ^1.0.18
    '@endo/pass-style': ^1.6.3
    '@endo/patterns': ^1.7.0
    '@endo/promise-kit': ^1.1.13
    '@endo/ses-ava': ^1.3.2
    '@endo/stream': ^1.2.13
    '@endo/stream-node': ^1.1.13
    '@endo/zip': ^1.0.11

# Ok for test env, reduces syncing overhead
enableScripts: true

nodeLinker: node-modules
