import fs from 'fs';
import { E } from '@endo/far';
import { deeplyFulfilled, makeMarshal } from '@endo/marshal';
import { decodeToJustin } from '@endo/marshal/src/marshal-justin.js';

import { makeCoreProposalBehavior } from './coreProposalBehavior.js';
import { createBundles } from './createBundles.js';

const { keys, values, fromEntries } = Object;

const { serialize } = makeMarshal();
const stringify = (x, pretty = undefined) =>
  decodeToJustin(JSON.parse(serialize(harden(x)).body), pretty);

export const htmlStartCommentPattern = new RegExp(`(${'<'})(!--)`, 'g');
export const htmlEndCommentPattern = new RegExp(`(--)(${'>'})`, 'g');
export const importPattern = new RegExp(
  '(^|[^.])\\bimport(\\s*(?:\\(|/[/*]))',
  'g',
);

const makeSet = (...args) => new Set(...args);

export const mergePermits = m => {
  const isObj = o => o !== null && typeof o === 'object';
  const merge = (left, right) => {
    if (left === undefined) {
      return right;
    }
    if (right === undefined) return left;
    if (isObj(left)) {
      if (isObj(right)) {
        const k12 = [...makeSet([...keys(left), ...keys(right)])];
        const e12 = k12.map(k => [k, merge(left[k], right[k])]);
        return fromEntries(e12);
      } else {
        return left;
      }
    } else {
      return typeof left === 'string' ? left : right;
    }
  };
  return values(m).reduce(merge);
};

// Neutralize HTML comments and import expressions.
export const defangEvaluableCode = code =>
  code
    .replace(importPattern, '$1import\\$2') // avoid SES_IMPORT_REJECTED
    .replace(htmlStartCommentPattern, '$1\\$2') // avoid SES_HTML_COMMENT_REJECTED
    .replace(htmlEndCommentPattern, '$1\\$2'); // avoid SES_HTML_COMMENT_REJECTED

export const makeWriteCoreProposal = (
  homeP,
  endowments,
  {
    getBundlerMaker,
    installInPieces,
    log = console.log,
    writeFile = fs.promises.writeFile,
  },
) => {
  const { board, zoe } = E.get(homeP);
  const { bundleSource, pathResolve } = endowments;

  let bundlerCache;
  const getBundler = () => {
    if (!bundlerCache) {
      bundlerCache = E(getBundlerMaker()).makeBundler({
        zoe,
      });
    }
    return bundlerCache;
  };

  const mergeProposalPermit = async (proposal, additionalPermits) => {
    const {
      sourceSpec,
      getManifestCall: [exportedGetManifest, ...manifestArgs],
    } = proposal;

    const manifestNs = await import(pathResolve(sourceSpec));

    // We only care about the manifest, not any restoreRef calls.
    const { manifest } = await manifestNs[exportedGetManifest](
      { restoreRef: x => `restoreRef:${x}` },
      ...manifestArgs,
    );

    const mergedPermits = mergePermits(manifest);
    return mergePermits({ mergedPermits, additionalPermits });
  };

  const writeCoreProposal = async (filePrefix, proposalBuilder) => {
    let mutex = Promise.resolve();
    // Install an entrypoint.
    const install = async (entrypoint, bundlePath) => {
      const bundler = getBundler();
      let bundle;
      if (bundlePath) {
        const bundleCache = pathResolve(bundlePath);
        await createBundles([[pathResolve(entrypoint), bundleCache]]);
        const ns = await import(bundleCache);
        bundle = ns.default;
      } else {
        bundle = await bundleSource(pathResolve(entrypoint));
      }

      // Serialise the installations.
      mutex = mutex.then(() => installInPieces(bundle, bundler));
      return mutex;
    };

    // Await a reference then publish to the board.
    const publishRef = async refP => {
      const ref = await refP;
      return E(board).getId(ref);
    };

    // Create the proposal structure.
    const proposal = await deeplyFulfilled(
      harden(proposalBuilder({ publishRef, install })),
    );
    const { sourceSpec, getManifestCall } = proposal;

    // Extract the top-level permit.
    const t = 'writeCoreProposal';
    const proposalPermit = await mergeProposalPermit(proposal, {
      consume: { board: t },
      evaluateInstallation: t,
      installation: { produce: t },
      modules: { utils: { runModuleBehaviors: t } },
    });

    // Get an install
    const manifestInstallRef = await publishRef(install(sourceSpec));

    const code = `\
// This is generated by writeCoreProposal; please edit!
/* eslint-disable */

const manifestInstallRef = ${stringify(manifestInstallRef)};
const getManifestCall = harden(${stringify(getManifestCall, true)});

// Make the behavior the completion value.
(${makeCoreProposalBehavior})({ manifestInstallRef, getManifestCall, E });
`;

    // Remove SES evaluation hazards.
    const defanged = defangEvaluableCode(code);

    // end-of-line whitespace disrupts YAML formatting
    const trimmed = defanged.replace(/[\r\t ]+$/gm, '');

    const proposalPermitJsonFile = `${filePrefix}-permit.json`;
    log(`creating ${proposalPermitJsonFile}`);
    await writeFile(
      proposalPermitJsonFile,
      JSON.stringify(proposalPermit, null, 2),
    );

    const proposalJsFile = `${filePrefix}.js`;
    log(`creating ${proposalJsFile}`);
    await writeFile(proposalJsFile, trimmed);

    log(`\
You can now run a governance submission command like:
  agd tx gov submit-proposal swingset-core-eval ${proposalPermitJsonFile} ${proposalJsFile} \\
    --title="Enable <something>" --description="Evaluate ${proposalJsFile}" --deposit=1000000ubld \\
    --gas=auto --gas-adjustment=1.2
`);
  };

  return writeCoreProposal;
};
