// @ts-check

export const Errors = {
  noKeplr: 'KEPLR_CONNECTION_ERROR_NO_KEPLR',
  enableKeplr: 'KEPLR_CONNECTION_ERROR_ENABLE_KEPLR',
  networkConfig: 'KEPLR_CONNECTION_ERROR_NETWORK_CONFIG',
  noSmartWallet: 'KEPLR_CONNECTION_ERROR_NO_SMART_WALLET',
};
