#! /bin/sh
cmd=${1+"$@"}
sdkTags=
otherTags=
if test -z "$cmd"; then
  cmd=echo
fi
for tag in $(git tag -l | egrep -e '@[0-9]+\.[0-9]+\.[0-9]+$'); do
  case $tag in
  @agoric/sdk@*) sdkTags="$sdkTags $tag" ;;
  @agoric/cosmos@*)
    # This logic publishes the golang tag needed for go get downloads.
    # Format needs to be vNN.MM.PP
    goTag=v$(echo "$tag" | sed -e 's/.*@//')
    git tag -f "$goTag" "$tag"
    otherTags="$otherTags $tag $goTag"
    ;;
  *) otherTags="$otherTags $tag" ;;
  esac
done

# Push the SDK tag separately so that it can trigger CI.
$cmd$otherTags && $cmd$sdkTags
exit $?
