#! /bin/sh
# Invokes `echo` or a specified other command with a list of "...@<version>" and
# "v<version>" tags that include the HEAD commit, specifically handling
# "@agoric/sdk@<version>" tags into a dedicated invocation for CI convenience.
# Usage: $0 [<command> [<initial argument>...]]
cmd=${1+"$@"}
cmd=${cmd:-echo}
sdkTags=
otherTags=
for tag in $(git tag -l --contains HEAD | grep -E '(@|^v)[0-9.]+(-[^.]*\.[0-9.]+)?$'); do
	case $tag in
	@agoric/sdk@*) sdkTags="$sdkTags $tag" ;;
	*) otherTags="$otherTags $tag" ;;
	esac
done

# Push the SDK tag separately so that it can trigger CI.
$cmd $otherTags && $cmd $sdkTags
