#! /usr/bin/perl
use warnings;
use strict;

my $difftarget = $ARGV[0] || 'HEAD';

open(my $fh, "git diff $difftarget|") or die "cannot get diff from $difftarget: $!";
my $cllines;
my $lookingForCurrentVersion = 0;
my $bumpOnly = 0;
my $line;

print "## Packages that have NEWS.md updates\n\n\`\`\`diff\n";

while ($line = <$fh>) {
  if ($line =~ /^--- a\/(.*)\/CHANGELOG.md/) {
    $cllines = $line;
    $lookingForCurrentVersion = 1;
  } elsif ($cllines) {
    #print "$line";
    if ($line =~ /^diff /) {
      # Found the next file.
      if ($cllines) {
        print $cllines;
      }
      $cllines = '';
    } elsif ($line =~ /^\+\*\*Note:\*\* Version bump only for package/) {
      $cllines = '';
    } else {
      $cllines .= $line;
    }
  }
}

if ($cllines) {
  print $cllines;
}

print "\`\`\`\n";
