// @jessie-check

export const AG_COSMOS_INIT = 'AG_COSMOS_INIT';
export const SWING_STORE_EXPORT = 'SWING_STORE_EXPORT';
export const BEGIN_BLOCK = 'BEGIN_BLOCK';
export const CALCULATE_FEES_IN_BEANS = 'CALCULATE_FEES_IN_BEANS';
export const CORE_EVAL = 'CORE_EVAL';
export const DELIVER_INBOUND = 'DELIVER_INBOUND';
export const END_BLOCK = 'END_BLOCK';
export const COMMIT_BLOCK = 'COMMIT_BLOCK';
export const AFTER_COMMIT_BLOCK = 'AFTER_COMMIT_BLOCK';
export const IBC_EVENT = 'IBC_EVENT';
export const PLEASE_PROVISION = 'PLEASE_PROVISION';
export const VBANK_BALANCE_UPDATE = 'VBANK_BALANCE_UPDATE';
export const WALLET_ACTION = 'WALLET_ACTION';
export const WALLET_SPEND_ACTION = 'WALLET_SPEND_ACTION';
export const INSTALL_BUNDLE = 'INSTALL_BUNDLE';
export const VTRANSFER_IBC_EVENT = 'VTRANSFER_IBC_EVENT';
