name: Agoric SDK build Node.js
description: 'Build Node.js and cache built files'

inputs:
  node-version:
    description: 'The version of Node.js to use'
    required: true

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ inputs.node-version }}
    - name: cache node modules
      uses: actions/cache@v1
      with:
        path: ~/.cache/yarn
        key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    # 'yarn install' must be done at the top level, to build all the
    # cross-package symlinks
    - name: yarn install
      run: yarn install
      shell: bash
    # We do a diff instead of using --frozen-lockfile because
    # - it doesn't detect deletions from yarn.lock (see https://github.com/Agoric/agoric-sdk/pull/4646#discussion_r814034842)
    # - the diff provides diagnostic info of what changed
    - name: fail if git checkout differs
      run: git diff --exit-code
      shell: bash
    - name: check dependencies
      run: yarn check-dependencies
      shell: bash
    # 'yarn build' loops over all workspaces
    - name: yarn build
      shell: bash
      run: yarn build

    - uses: ./.github/actions/save-node
      with:
        node-version: ${{ inputs.node-version }}
