name: Post Test Functions
description: 'Runs test uploading and coverage uploading'

inputs:
  codecov-token:
    description: 'token for codecov'
    required: false
    default: ''
  datadog-token:
    description: 'token for datadog'
    required: false
    default: ''
  datadog-site:
    description: 'site for datadog'
    required: false
    default: 'us3.datadoghq.com'

runs:
  using: composite
  steps:
    - name: upload tests
      shell: bash
      if: ${{ github.repository_owner == 'agoric' }} && (success() || failure())
      env:
        DD_ENV: ci
        DATADOG_SITE: ${{ inputs.datadog-site }}
      continue-on-error: true
      run: |
        ./scripts/ci-collect-testruns.sh
        if [ "${{ inputs.datadog-token }}" != "" ]; then
          export DATADOG_API_KEY="${{ inputs.datadog-token }}"
          export DD_ENV="ci"
          export DD_SITE="${{ inputs.datadog-site }}"

          npx @datadog/datadog-ci --version 
          timeout 30 npx @datadog/datadog-ci junit upload --service agoric-sdk ./packages/*/junit.xml
        fi
    - name: upload coverage prepare
      shell: bash
      id: coverage-prep
      if: ${{ github.repository_owner == 'agoric' }} && (success() || failure())
      run: |
        if [ "${{ inputs.codecov-token }}" != "" ]; then
          # delete v8 coverage jsons to reduce noise
          find . -name "coverage*.json" -delete
          echo "skip=false" >> $GITHUB_OUTPUT
        else
          echo "skip=true" >> $GITHUB_OUTPUT
        fi
    - name: Upload coverage reports to Codecov
      if: ${{ github.repository_owner == 'agoric' }} && ${{ steps.coverage-prep.outputs.skip == 'false' }} && (success() || failure())
      uses: codecov/codecov-action@v4
      continue-on-error: true
      with:
        token: ${{ inputs.codecov-token }}
