COQ_VER ?= 8.9.1
ifeq ($(COQ_VER),8.9.1)
OCAML_VER ?= 4.07.1
EXTRA_OPAM_PKGS ?=
else
OCAML_VER ?= 4.14.1
EXTRA_OPAM_PKGS ?= coq-iris coq-iris-heap-lang vsrocq-language-server.$(VSROCQ_LSP_VER)
endif
OPAM_SWITCH ?= ocpl-coq-$(COQ_VER)-ocaml-$(OCAML_VER)
VSROCQ_LSP_VER ?= 2.3.4
COQFLAGS := -Q ocpl OCPL
DEFAULT_SOURCES := ocpl/modern_heap.v ocpl/modern_lifting.v ocpl/modern_on_val.v ocpl/modern_robust_safety.v jessie_counter_heaplang.v
SOURCES ?= $(DEFAULT_SOURCES)
VO_TARGETS := $(patsubst %.v,%.vo,$(SOURCES))
DEPFILE := .coqdeps.d
OPAM_ENV = eval "$$(opam env --switch=$(OPAM_SWITCH))"

.PHONY: help ubuntu-deps opam-init switch install build clean env

help:
	@echo "Targets:"
	@echo "  ubuntu-deps  Install system packages needed on Ubuntu"
	@echo "  opam-init    Initialize opam if needed"
	@echo "  switch       Create/select opam switch $(OPAM_SWITCH)"
	@echo "  install      Install Coq plus EXTRA_OPAM_PKGS in the switch"
	@echo "  build        Incrementally build Coq sources in SOURCES"
	@echo "  clean        Remove Coq build artifacts"
	@echo "  env          Print shell command to load the switch env"
	@echo ""
	@echo "Defaults:"
	@echo "  COQ_VER=$(COQ_VER)"
	@echo "  OCAML_VER=$(OCAML_VER)"
	@echo "  OPAM_SWITCH=$(OPAM_SWITCH)"
	@echo "  EXTRA_OPAM_PKGS=$(EXTRA_OPAM_PKGS)"

ubuntu-deps:
	sudo apt update
	sudo apt install -y build-essential m4 pkg-config bubblewrap opam git

opam-init:
	opam init --disable-sandboxing -y

switch:
	opam switch create $(OPAM_SWITCH) ocaml-base-compiler.$(OCAML_VER) || opam switch set $(OPAM_SWITCH)
	eval "$$(opam env --switch=$(OPAM_SWITCH))" && ocaml -version

install:
	$(OPAM_ENV) && \
	opam repo add coq-released https://coq.inria.fr/opam/released -y && \
	opam update && \
	opam install -y coq.$(COQ_VER) $(EXTRA_OPAM_PKGS)

build: $(VO_TARGETS)

$(DEPFILE): $(SOURCES)
	@printf '%s\n' "# Autogenerated by coqdep for SOURCES=$(SOURCES)" > $(DEPFILE)
	@$(OPAM_ENV) && coqdep $(COQFLAGS) $(SOURCES) >> $(DEPFILE)

-include $(DEPFILE)

%.vo: %.v $(DEPFILE)
	@echo "coqc $<"
	@$(OPAM_ENV) && coqc $(COQFLAGS) $<

clean:
	rm -f *.vo *.vos *.vok .*.aux *.glob $(DEPFILE)

env:
	@echo 'eval "$$(opam env --switch=$(OPAM_SWITCH))"'
