OPAM_SWITCH ?= iris
OCAML_VER ?= 4.14.1
COQ_VER ?= 8.18.0
VSROCQ_LSP_VER ?= 2.3.4
ALL_V_SOURCES := $(sort $(wildcard *.v))
DEFAULT_SOURCES := $(filter-out hello_bad.v,$(ALL_V_SOURCES))
SOURCES ?= $(DEFAULT_SOURCES)
VO_TARGETS := $(patsubst %.v,%.vo,$(SOURCES))
DEPFILE := .coqdeps.d
OPAM_ENV = eval "$$(opam env --switch=$(OPAM_SWITCH))"

.PHONY: help ubuntu-deps opam-init switch install build clean env

help:
	@echo "Targets:"
	@echo "  ubuntu-deps  Install system packages needed on Ubuntu"
	@echo "  opam-init    Initialize opam if needed"
	@echo "  switch       Create/select opam switch $(OPAM_SWITCH)"
	@echo "  install      Install Coq and Iris in the switch"
	@echo "  build        Incrementally build Coq sources in SOURCES"
	@echo "  clean        Remove Coq build artifacts"
	@echo "  env          Print shell command to load the switch env"
	@echo ""
	@echo "Variables:"
	@echo "  SOURCES      Space-separated .v files to compile"
	@echo ""
	@echo "Examples:"
	@echo '  make -f iris.mk build'
	@echo '  make -f iris.mk build SOURCES="jessie_lang.v jessie_justin.v"'

ubuntu-deps:
	sudo apt update
	sudo apt install -y build-essential m4 pkg-config bubblewrap opam git

opam-init:
	opam init --disable-sandboxing -y

switch:
	# Use system OCaml if available to avoid long compiler build
	opam switch create $(OPAM_SWITCH) ocaml-system || opam switch set $(OPAM_SWITCH)
	eval "$$(opam env --switch=$(OPAM_SWITCH))" && ocaml -version

install:
	$(OPAM_ENV) && \
	opam repo add coq-released https://coq.inria.fr/opam/released -y && \
	opam update && \
	opam install -y coq.$(COQ_VER) coq-iris vsrocq-language-server.$(VSROCQ_LSP_VER)

build: $(VO_TARGETS)

$(DEPFILE): $(SOURCES)
	@printf '%s\n' "# Autogenerated by coqdep for SOURCES=$(SOURCES)" > $(DEPFILE)
	@$(OPAM_ENV) && coqdep $(SOURCES) >> $(DEPFILE)

-include $(DEPFILE)

%.vo: %.v $(DEPFILE)
	@echo "coqc $<"
	@$(OPAM_ENV) && coqc $<

clean:
	rm -f *.vo *.vos *.vok .*.aux *.glob $(DEPFILE)

env:
	@echo 'eval "$$(opam env --switch=$(OPAM_SWITCH))"'
