name: Run Benchmarks

# run on changes to trunk, and also nightly

on:
  push:
    branches: [master]
  schedule:
    # Run an hour after the daily test-all-packages.yml job, so it can
    # populate the build caches
    - cron: '47 6 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/restore-node
        with:
          node-version: 'node-new'

      - name: yarn bench (boot)
        shell: bash
        run: |
          cd packages/boot && yarn bench
          echo "METRIC_VALUE=`cat benchmark-stress-vaults.json | jq .avgPerVaultMs`" >> $GITHUB_ENV

      - uses: ./.github/actions/publish-metric
        with:
          metric: 'vats.perf.avgPerVaultMs'
          metric-value: ${{env.METRIC_VALUE}}
          datadog-token: ${{ secrets.DATADOG_API_KEY }}
