name: Post Integration Test Comment on Base Branch Change

on:
  pull_request:
    types:
      - edited

jobs:
  trigger:
    runs-on: ubuntu-latest
    if: ${{ github.event.changes.base && github.event.pull_request.base.ref == 'master' }}
    steps:
      - name: Post a comment on the PR
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: "Base branch is changed to master. Please re-run the integration tests by adding 'force:integration' label."
            })
