name: Multichain E2E Tests

on:
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Select which test to run'
        type: choice
        required: true
        options:
          - orchestration-api-hermes
          - fast-usdc-hermes
          - orchestration-api-go-relayer
          - fast-usdc-go-relayer
  workflow_call:

jobs:
  orchestration-api-hermes:
    name: Orchestration API - Hermes
    if: |
      github.event_name == 'workflow_call' ||
      github.event_name == 'pull_request' ||
      (github.event_name == 'workflow_dispatch' && inputs.test_type == 'orchestration-api-hermes')
    uses: ./.github/workflows/multichain-e2e-template.yml
    with:
      config: config.yaml
      test_command: yarn test:main

  fast-usdc-hermes:
    name: Fast USDC - Hermes
    if: |
      github.event_name == 'workflow_call' ||
      github.event_name == 'pull_request' ||
      (github.event_name == 'workflow_dispatch' && inputs.test_type == 'fast-usdc-hermes')
    uses: ./.github/workflows/multichain-e2e-template.yml
    with:
      config: config.fusdc.yaml
      test_command: yarn test:fast-usdc

  orchestration-api-go-relayer:
    name: Orchestration API - Go Relayer
    # run on dispatch only
    if: github.event_name == 'workflow_dispatch' && inputs.test_type == 'orchestration-api-go-relayer'
    uses: ./.github/workflows/multichain-e2e-template.yml
    with:
      config: config.go-relayer.yaml
      test_command: RELAYER_TYPE=go-relayer yarn test:main

  fast-usdc-go-relayer:
    name: Fast USDC - Go Relayer
    # run on dispatch only
    if: github.event_name == 'workflow_dispatch' && inputs.test_type == 'fast-usdc-go-relayer'
    uses: ./.github/workflows/multichain-e2e-template.yml
    with:
      config: config.fusdc.go-relayer.yaml
      test_command: RELAYER_TYPE=go-relayer yarn test:fast-usdc
